server:
  port: 8081

logging:
  level:
    cn.solairelight.*: debug


#SolairelightConfig example
solairelight:
  enable: true
  websocket-path: /path
  standalone: false
  zookeeper:
    host-port: 127.0.0.1:2181
  secure:
    metadata-key: Metadata-Token
    public-key-base64: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEEVs/o5+uQbTjL3chynL4wXgUg2R9q9UU8I5mEovUf86QZ7kOBIjJwqnzD1omageEHWwHdBO6B+dFabmdT9POxg==
    key-provider: https://key-provider.org/
  message:
    protocol: protobuf
  session:
    idle: 600 #seconds
    max-number: 20000
  forward:
    enable: true
    forwardHeader: Host
    routes:
      - uri: http://localhost:8081/example
        predicate:
          message: version==v1
          header: h1==v1
          operator: and
