server:
  port: 8081

logging:
  level:
    io.github.joelou.solairelight.*: debug

management:
  endpoints:
    web:
      exposure:
        include: nodeOverview
      discovery:
        enabled: true

#SolairelightConfig example
solairelight:
  enable: true
  websocket-path: /solairelight
  cluster:
    enable: true
    node-id-suffix: 1
  secure:
    metadata-key: Metadata-Token
    public-key-base64: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu1SU1LfVLPHCozMxH2Mo4lgOEePzNm0tRgeLezV6ffAt0gunVTLw7onLRnrq0/IzW7yWR7QkrmBL7jTKEn5u+qKhbwKfBstIs+bMY2Zkp18gnTxKLxoS2tFczGkPLPgizskuemMghRniWaoLcyehkd3qqGElvW/VDL5AaWTg0nLVkjRo9z+40RQzuVaE8AkAFmxZzow3x+VJYKdjykkJ0iT9wCS0DRTXu269V264Vf/3jvredZiKRkgwlL9xNAwxXFg0x/XFw005UWVRIkdgcKWTjpBP2dPwVZ4WWC+9aGVd+Gyn1o0CLelf4rEjGoXbAAEgAqeGUxrcIlbjXfbcmwIDAQAB
  session:
    idle: 600 #seconds
    max-number: 20000
  forward:
    enable: true
    forwardHeader: Host
    routes:
      - uri: http://localhost:8081/example
        predicate:
          message: sampleKey=='v1'
          session-header: h1==v1
          operator: or
