server:
  port: 8081

logging:
  level:
    io.github.joelou.solairelight.*: debug


#SolairelightConfig example
solairelight:
  enable: true
  websocket-path: /solairelight
  cluster:
    enable: true
    node-id-suffix: 1
  secure:
    metadata-key: Metadata-Token
    public-key-base64: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEEVs/o5+uQbTjL3chynL4wXgUg2R9q9UU8I5mEovUf86QZ7kOBIjJwqnzD1omageEHWwHdBO6B+dFabmdT9POxg==
  session:
    idle: 600 #seconds
    max-number: 20000
  forward:
    enable: true
    forwardHeader: Host
    routes:
      - uri: http://localhost:8081/example
        predicate:
          message: sampleKey=='v1'
          session-header: h1==v1
          operator: or
