spring:
  cloud:
    gateway:
      routes:
        - id: solairelight-route
          uri: solairelight://broadcast
          predicates:
          - Path=/solairelight/broadcast
        - id: solairelight-ws-route
          uri: lb:ws://solairelight
          predicates:
          - Path=/solairelight
solairelight:
  websocket:
    routing:
      mode: redirect